### ISSUE TITLE
Add a licence?

### ISSUE THREAD

**Issue by jamessergeant** [fbaeuerlein/MurtyAlgorithm#2]
Just wondering whether you intend to add a licence to this repository?

**Comment by fbaeuerlein** [comment]
Thanks for the hint. I add one in the next days.

**Comment by fbaeuerlein** [comment]
Fixed with https://github.com/fbaeuerlein/MurtyAlgorithm/commit/fa2d51f65c6b89ab79b624735cecd3a60c30110f
